# Generated by Django 3.0.2 on 2020-01-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_braintree_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'order'},
        ),
    ]
