# Generated by Django 3.0.2 on 2020-01-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
